/* MTI_DPI */

/*
 * Copyright 2002-2015 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_SCOREBOARD
#define INCLUDED_SCOREBOARD

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


#ifndef MTI_INCLUDED_TYPEDEF_scoreboard_snapshot_t
#define MTI_INCLUDED_TYPEDEF_scoreboard_snapshot_t

typedef struct {
    int cycle;
    int pc;
    int pc_next;
    int opcode;
    int cause;
    int mask;
    int epc;
    int status;
    int reg_bank[32];
}  scoreboard_snapshot_t;

#endif


DPI_LINK_DECL DPI_DLLESPEC
int
cycle(
    scoreboard_snapshot_t* trace);

DPI_LINK_DECL DPI_DLLESPEC
int
dump_sram(
    unsigned int* dst,
    int size);

DPI_LINK_DECL DPI_DLLESPEC
int
set_io(
    int pin,
    int val);

DPI_LINK_DECL DPI_DLLESPEC
int
setup(
    const unsigned int* src,
    int size,
    int debug);

DPI_LINK_DECL int
log_uart(
    unsigned char c);

DPI_LINK_DECL int
terminate(
    int errcode);

#endif 
