onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_top/dut/perif/clk_i
add wave -noupdate /tb_top/dut/perif/rst_i
add wave -noupdate /tb_top/dut/perif/addr_i
add wave -noupdate /tb_top/dut/perif/data_i
add wave -noupdate /tb_top/dut/perif/data_o
add wave -noupdate /tb_top/dut/perif/sel_i
add wave -noupdate /tb_top/dut/perif/wr_i
add wave -noupdate /tb_top/dut/perif/irq_o
add wave -noupdate /tb_top/dut/perif/gpioa_in
add wave -noupdate /tb_top/dut/perif/gpioa_out
add wave -noupdate /tb_top/dut/perif/gpioa_ddr
add wave -noupdate /tb_top/dut/perif/segment
add wave -noupdate /tb_top/dut/perif/class
add wave -noupdate /tb_top/dut/perif/device
add wave -noupdate /tb_top/dut/perif/funct
add wave -noupdate /tb_top/dut/perif/paaltcfg0
add wave -noupdate /tb_top/dut/perif/s0cause
add wave -noupdate /tb_top/dut/perif/gpiocause
add wave -noupdate /tb_top/dut/perif/gpiocause_inv
add wave -noupdate /tb_top/dut/perif/gpiomask
add wave -noupdate /tb_top/dut/perif/timercause
add wave -noupdate /tb_top/dut/perif/timercause_inv
add wave -noupdate /tb_top/dut/perif/timermask
add wave -noupdate /tb_top/dut/perif/paddr
add wave -noupdate /tb_top/dut/perif/paout
add wave -noupdate /tb_top/dut/perif/pain
add wave -noupdate /tb_top/dut/perif/pain_inv
add wave -noupdate /tb_top/dut/perif/pain_mask
add wave -noupdate /tb_top/dut/perif/timer0
add wave -noupdate /tb_top/dut/perif/timer1
add wave -noupdate /tb_top/dut/perif/timer1_ctc
add wave -noupdate /tb_top/dut/perif/timer1_ocr
add wave -noupdate /tb_top/dut/perif/timer1_pre
add wave -noupdate /tb_top/dut/perif/timer1_set
add wave -noupdate /tb_top/dut/perif/int_gpio
add wave -noupdate /tb_top/dut/perif/int_timer
add wave -noupdate /tb_top/dut/perif/int_gpioa
add wave -noupdate /tb_top/dut/perif/int_timer1_ocr
add wave -noupdate /tb_top/dut/perif/int_timer1_ctc
add wave -noupdate /tb_top/dut/perif/tmr1_pulse
add wave -noupdate /tb_top/dut/perif/tmr1_dly
add wave -noupdate /tb_top/dut/perif/tmr1_dly2
add wave -noupdate /tb_top/dut/perif/paalt0
add wave -noupdate /tb_top/dut/iface/clk
add wave -noupdate /tb_top/dut/iface/reset
add wave -noupdate /tb_top/dut/iface/stall
add wave -noupdate /tb_top/dut/iface/address
add wave -noupdate /tb_top/dut/iface/data_read
add wave -noupdate /tb_top/dut/iface/data_write
add wave -noupdate /tb_top/dut/iface/data_we
add wave -noupdate /tb_top/dut/iface/extio_in
add wave -noupdate /tb_top/dut/iface/extio_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {5000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 265
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {127149750 ps}
